### ISSUE TITLE
dtwc_delivery_time options are permanently removed when selecting today

### ISSUE THREAD

**Issue by FelixVicis** [deviodigital/delivery-times-for-woocommerce#1]
https://github.com/deviodigital/delivery-times-for-woocommerce/blob/662e4b0a48fb5beb34f758140ab2a5381bb7c321/public/js/dtwc-public.js#L62

By removing the possible options instead of hiding them, or storing them to restore the option later, you can never select the removed values again.

For example. My store delivers from 9:00 to 16:00. If I, as a customer, select a delivery date of today at a time of 14:00. I will see the correct times (14:00 to 16:00). But if I then select the next day, I still only see 14:00 to 16:00 instead of the expected 9:00 to 16:00.

**Comment by robertdevore** [comment]
Thanks for opening this issue @FelixVicis 💯 

I've got a code fix in place ([commits](https://github.com/deviodigital/delivery-times-for-woocommerce/commits/master)) and will be releasing version 1.5 ASAP in the official WP repo.

Thanks!
