### ISSUE TITLE
The dtwc_delivery_date will still offer times today even if there are none left

### ISSUE THREAD

**Issue by FelixVicis** [deviodigital/delivery-times-for-woocommerce#2]
https://github.com/deviodigital/delivery-times-for-woocommerce/blob/b694e9fdcacd4805fab23782734b39abd3b11a8e/public/class-dtwc-public.php#L160

In the case of same day shipping, the date picker should should check to make sure that there are times available past prep_time today. Otherwise, it should offer the next possible date.

**Comment by robertdevore** [comment]
Thanks for opening this issue @FelixVicis 💯 

I've got a code fix in place ([commits](https://github.com/deviodigital/delivery-times-for-woocommerce/commits/master)) and will be releasing version 1.5 ASAP in the official WP repo.

Thanks!
